name: Build Orchid APK

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Get Code
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        echo "Android build starts here"
